ref:
  # TODO - what's going on here
  bc1_map: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1_RT_replace.txt
  barcodes: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1r2r3.txt

  annot_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M32/gencode.vM32.chr_patch_hapl_scaff.annotation.gtf.gz
  annot: ref/gencode.vM32.gtf.gz
  fa_link: https://hgdownload.soe.ucsc.edu/goldenPath/mm39/bigZips/mm39.fa.gz
  fa: ref/mm39.fa.gz

  kallisto:
    t2g: ref/kallisto/c57bl6j.t2g
    ind: ref/kallisto/c57bl6j.idx
    fa: ref/kallisto/c57bl6j.cdna.fasta
    na: ref/kallisto/c57bl6j.nascent.fasta
    c1: ref/kallisto/c57bl6j.c1
    c2: ref/kallisto/c57bl6j.c2

  klue:
    t2g: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/klue_ref/{mult_genotype_1}_{mult_genotype_2}.t2g
    ind: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/klue_ref/{mult_genotype_1}_{mult_genotype_2}.idx

raw:
  # fastq: fastq/{plate}_{subpool}_{lane}_{read}_001.fastq.gz
  fastq_r1: fastq/{plate}_{subpool}_{run}_{lane}_R1_001.fastq.gz
  fastq_r2: fastq/{plate}_{subpool}_{run}_{lane}_R2_001.fastq.gz

# TODO - make other output directories (ie the ones not in counts_unfiltered_modified)
# temporary?
kallisto:
  cgb: kallisto/{plate}/{subpool}/counts_unfiltered_modified/cells_x_genes.barcodes.txt
  cggn: kallisto/{plate}/{subpool}/counts_unfiltered_modified/cells_x_genes.genes.names.txt
  cgg: kallisto/{plate}/{subpool}/counts_unfiltered_modified/cells_x_genes.genes.txt
  adata: kallisto/{plate}/{subpool}/counts_unfiltered_modified/adata.h5ad
  mtx: kallisto/{plate}/{subpool}/counts_unfiltered_modified/cells_x_genes.total.mtx
  bus: kallisto/{plate}/{subpool}/output.bus
  bus_modified_unfilt: kallisto/{plate}/{subpool}/output_modified.unfiltered.bus
  bus_unfilt: kallisto/{plate}/{subpool}/output.unfiltered.bus

  filt_adata: kallisto/{plate}/{subpool}/filtered/adata.h5ad
  genotype_adata: kallisto/{plate}/{subpool}/adata.h5ad

klue:
  cgb: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/counts_unfiltered_modified/cells_x_genes.barcodes.txt
  cggn: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/counts_unfiltered_modified/cells_x_genes.genes.names.txt
  cgg: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/counts_unfiltered_modified/cells_x_genes.genes.txt
  adata: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/counts_unfiltered_modified/adata.h5ad
  bus: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/output.bus
  bus_modified_unfilt: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/output_modified.unfiltered.bus
  bus_unfilt: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/output.unfiltered.bus

  filt_adata: klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/filtered/adata.h5ad

  # version with all genotypes
  genotype_counts: klue/{plate}/{subpool}/genotype_counts.tsv

scrublet:
  # TODO sample will be combo of {tissue}_{genotype}_{sex}_{age}_{mouse_id}
  adata: scrublet/{plate}/{sample}/{subpool}/adata.h5ad
  scrub_adata: scrublet/{plate}/{sample}/{subpool}/scrubbed_adata.h5ad

tissue:
  adata: ./{plate}/{tissue}/adata.h5ad
